# Generated by Django 4.2.1 on 2023-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefields',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeefields',
            name='employee_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
